import {
    formatCoordinatesHTML,
    generateTextTableLandscape
} from "@/app/utils/map/map-utils";

import {
    generateSolarTextTable
} from "@/app/utils/map/solar-utils";
import {generateWindTextTable} from "@/app/utils/map/wind-utils";

const formatResponseData = (data) => {
    if (data) {
        return `Your Polygon
    
    Your polygon area: ${data.initial_polygon_area.toFixed(5)} km²
    
    Coordinates:\n${formatCoordinatesHTML(data.coordinates)}
    
    Your Polygon Landscape Types Classification
    
${generateTextTableLandscape(data.area)}
   

Suitable Territory Polygon
    
${suitablePolygonTextPart(data)}
    
    
Energy Output Prediction
${energyOutputPrediction(data)}

Visit Resources Page, there you can find Formula for calculation energy output and all landscape types


${recommendationsText(data)}
`
    } else {
        return `We are sorry to inform, but we unable to generate report for your polygon`
    }
};

function energyOutputPrediction(data) {
    if (data?.energy_output_stats?.month_energy_stats !== undefined && data?.energy_output_stats?.month_energy_stats !== null) {
        if (data?.type === "wind") {
            return generateWindTextPart(data)
        }
        return generateSolarTextPart(data)
    } else {
        return `We are sorry to inform, but we unable to generate energy output prediction for your polygon`
    }
}

function recommendationsText(data) {
    console.log(data?.type)
    if (data?.type === "wind") {
        return `
----------------------------

Here are some recommendations and useful resources:
    - ЗАКОН УКРАЇНИ Про альтернативні джерела енергії: https://zakon.rada.gov.ua/laws/show/555-15#Text
    - ЗАКОН УКРАЇНИ Про ринок електиричної енергії: https://zakon.rada.gov.ua/laws/show/2019-19#Text
    - Please note that if you are planning to build a solar panel power plant, you do not need to decide on the type of your power plant. We recommend that you familiarize yourself with the types of solar power plants in detail here: https://www.solargarden.com.ua/typy-sonyachnyh-elektrostantsiy-ih-efektyvnist-perevahy-i-nedoliky/
    - There are many types of solar panels with different technical characteristics. Monocrystalline panels, for example, usually have higher efficiency than polycrystalline panels, but can be more expensive. You can learn about the types of solar panels here: https://www.greenmatch.co.uk/blog/2015/09/types-of-solar-panels, https://www.solarchoice.net.au/solar-panels/sizes/
    - Pay attention to quality and safety standards when choosing components for your solar system. This will ensure the reliability and durability of the installation. Information on standards can be found at the National Standardization Body of Ukraine or on the websites of certification agencies.
`
    } else {
        return ``
    }
}

function suitablePolygonTextPart(data) {
    if (data.suitable_polygon_area && data.crop) {
        return `    Suitable polygon area: ${data.suitable_polygon_area.toFixed(5)} km²
    
    Coordinates:\n${formatCoordinatesHTML(data.crop)}`
    }
    return `Unfortunately, there are no suitable areas within your range.`
}

function generateSolarTextPart(data) {
    return `This document contains information on how much energy can be generated by solar panels in a given area. Please note that the calculations
are approximate and have been based on constant values, which may differ from the values for the type of panel you choose.

${generateSolarTextTable(data?.energy_output_stats?.month_energy_stats)}`
}

function generateWindTextPart(data) {
    return `This document contains information on how much energy can be generated by wind turbins in a given area. Please note that the calculations
are approximate and have been based on constant values, which may differ from the values for the type of turbins you choose.

${generateWindTextTable(data?.energy_output_stats)}`
}



export default formatResponseData;