import {
    formatCoordinatesHTML,
    generateTextTableLandscape, generateTextTableWeather
} from "@/app/utils/map/map-utils";

function generateWeatherTextPart(data) {
    if (data?.energy_output_stats?.month_energy_stats !== undefined && data?.energy_output_stats?.month_energy_stats !== null) {
        return `This document contains information on how much energy can be generated by solar panels in a given area. Please note that the calculations
are approximate and have been based on constant values, which may differ from the values for the type of panel you choose.

${generateTextTableWeather(data?.energy_output_stats?.month_energy_stats)}`
    } else {
        return `We are sorry to inform, but we unable to generate energy output prediction for your polygon`
    }
}

function suitablePolygonTextPart(data) {
    if (data.suitable_polygon_area && data.crop) {
        return `    Suitable polygon area: ${data.suitable_polygon_area.toFixed(5)} km²
    
    Coordinates:\n${formatCoordinatesHTML(data.crop)}`
    }
    return `Unfortunately, there are no suitable areas within your range.`
}

const formatResponseData = (data) => {
    if (data) {
        return `Your Polygon
    
    Your polygon area: ${data.initial_polygon_area.toFixed(5)} km²
    
    Coordinates:\n${formatCoordinatesHTML(data.coordinates)}
    
    Your Polygon Landscape Types Classification
    
${generateTextTableLandscape(data.area)}
   

Suitable Territory Polygon
    
${suitablePolygonTextPart(data)}
    
    
Energy Output Prediction
${generateWeatherTextPart(data)}
`
    } else {
        return `We are sorry to inform, but we unable to generate report for your polygon`
    }
};

export default formatResponseData;